source ./vars.txt

echo "Hello World " >> out.txt

echo "This is output is generated by script run through jenkins and git " >> out.txt

echo " SUiCCESS " >> out.txt

echo "JB_HTTP_PORT=$JB_HTTP_PORT" >> out.txt
echo "MANO_HOME=$MANO_HOME" >> out.txt
